# Generated by Django 3.1.4 on 2021-03-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=200)),
                ('marital_education', models.CharField(max_length=200)),
                ('default', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('targeted', models.CharField(max_length=200)),
                ('marital', models.CharField(max_length=200)),
                ('housing', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('loan', models.CharField(max_length=200)),
            ],
        ),
    ]
